
# MongoDB DB Setting Value 추가 --------------------------------------------------------------------
# 참고: https://www.tutorialsbuddy.com/spring-batch-with-mongodb-example
spring:
  data:
    mongodb:
      # DB 관련 정보는 '{}'로 묶어 놓음.
      uri: mongodb+srv://chae:4879@cluster0.aolss.mongodb.net/sample_supplies?retryWrites=true&w=majority
      database: sample_supplies
  profiles:
    active: mongoDB
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:sample_airbnb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
# -------------------------------------------------------------------------------------------------